create table film_final (
	film_id INT,
	ranking INT,
	film_title VARCHAR(50),
	director VARCHAR(50),
	genre_id INT
);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (1, 73, 'Ikiru', 'Bonita Hek', 1);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (2, 234, 'Withnail & I', 'Faunie Strowthers', 2);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (3, 159, 'Maria', 'Bernie Bennit', 3);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (4, 122, 'Another Happy Day', 'Sheffie Danshin', 4);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (5, 164, 'Juarez', 'Bailie Hazle', 5);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (6, 172, 'Embodiment of Evil (Encarnação do Demônio)', 'Roselin Hartas', 6);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (7, 235, 'Jet Pilot', 'Gerda Yourell', 7);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (8, 152, 'Kung Fu Panda: Secrets of the Furious Five', 'Jarib Durber', 8);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (9, 157, 'Mayerling', 'Byrom Corrao', 9);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (10, 28, 'Newlyweds', 'Chrisy Sackes', 10);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (11, 226, 'People That Time Forgot, The', 'Nixie Critch', 11);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (12, 44, 'Traffic Affairs (Mitfahrer)', 'Jonell Loude', 12);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (13, 167, 'Agent Vinod', 'Amy Bear', 13);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (14, 24, 'Table 7', 'Tomlin Ungerer', 14);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (15, 141, 'Stella Street', 'Derward Jurkiewicz', 15);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (16, 89, '''Round Midnight', 'Salvidor Laherty', 16);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (17, 156, 'Lizard in a Woman''s Skin, A (Lucertola con la pelle di donna, Una)', 'Brook Petruszka', 17);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (18, 144, 'Miss Julie', 'Murray La Grange', 18);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (19, 177, 'What If... (An...)', 'Antonietta Jencken', 19);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (20, 106, 'MC5*: A True Testimonial', 'Andree Kalvin', 20);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (21, 60, 'Who Is Cletis Tout?', 'Kass Scad', 21);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (22, 196, 'Neighbors', 'Teodoor Challiss', 22);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (23, 224, 'Clubbed', 'Costanza Blitzer', 23);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (24, 213, 'Pina', 'Bibby Morfield', 24);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (25, 164, 'Macbeth in Manhattan', 'Kettie Yude', 25);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (26, 228, 'Honor Among Thieves (Adieu l''ami) (Farewell, Friend)', 'Piotr Sharphouse', 26);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (27, 80, 'The Story of Robin Hood and His Merrie Men', 'Netta Vaskin', 27);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (28, 206, 'Jazz Singer, The', 'Teodora Drache', 28);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (29, 226, 'How About You...', 'Lissa Road', 29);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (30, 204, 'Territories ', 'Tadeo Bendare', 30);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (31, 133, 'Christmas Story 2, A', 'Henrieta Kretschmer', 31);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (32, 111, 'Things Are Tough All Over', 'Annabell Shillito', 32);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (33, 119, 'Lynch', 'Buck Feldhammer', 33);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (34, 94, 'De la servitude moderne', 'Perry Roggero', 34);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (35, 46, 'True Stories', 'Panchito Ruddock', 35);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (36, 61, 'Beach Girls and the Monster, The', 'Chris O''Doogan', 36);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (37, 136, 'Divorce, Le', 'Prentiss Sealeaf', 37);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (38, 218, 'Member of the Wedding, The', 'Allie Mattes', 38);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (39, 27, 'Think Like a Man', 'Hillel Breede', 39);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (40, 247, 'Crime Lords of Tokyo', 'Walliw Rugge', 40);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (41, 168, 'Rio Rita', 'Amalea Zum Felde', 41);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (42, 191, 'Ballad of a Soldier (Ballada o soldate)', 'Hurley Ellor', 42);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (43, 184, 'My Father the Hero (Mon père, ce héros.)', 'Rollie M''Chirrie', 43);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (44, 68, 'Stolen Face', 'Alden Astman', 44);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (45, 89, 'Marie Krøyer', 'Nathanial Ganter', 45);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (46, 70, 'Suddenly', 'Jillayne Hailes', 46);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (47, 7, 'Without a Clue', 'Gusty Frostdick', 47);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (48, 241, 'Jay-Z: Made in America', 'Rebekkah Doran', 48);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (49, 129, 'La vérité si je mens !', 'Rinaldo Neal', 49);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (50, 189, 'Sex Ed', 'Nissie Schule', 50);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (51, 21, 'Rickshaw Man, The (Muhomatsu no issho)', 'Eric Sebastian', 51);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (52, 178, 'A Night in the Show', 'Jethro Mattiacci', 52);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (53, 95, 'Ten, The', 'Briano Linkie', 53);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (54, 177, 'ZMD: Zombies of Mass Destruction', 'Clint Peddie', 54);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (55, 129, 'Tenth Man, The', 'Natty Clitheroe', 55);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (56, 71, 'F for Fake (Vérités et mensonges)', 'Garner Kehri', 56);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (57, 27, 'Book of Shadows: Blair Witch 2', 'Durand Pascall', 57);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (58, 17, '11 Harrowhouse', 'Ulrikaumeko Ridehalgh', 58);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (59, 93, 'Misadventures of Margaret, The', 'Collin Greendale', 59);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (60, 91, 'Schizopolis', 'Willis Upchurch', 60);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (61, 123, 'Cain and Mabel', 'Amos Hollingby', 61);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (62, 231, 'Welfare', 'Micheil Castellaccio', 62);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (63, 41, 'Tall Blond Man with One Black Shoe, The (Le grand blond avec une chaussure noire)', 'Dionysus Blyth', 63);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (64, 223, 'Shrine, The', 'Hanny Belchambers', 64);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (65, 44, 'Dead Zone, The', 'Mattheus Ellacott', 65);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (66, 99, 'Brain, The', 'Wyndham Eddington', 66);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (67, 209, 'Beach Red', 'Allayne Serjent', 67);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (68, 134, 'Here Comes Cookie', 'Jayme Oboy', 68);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (69, 248, 'Ginger Snaps Back: The Beginning', 'Ivie Saing', 69);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (70, 117, 'Don Quixote (Don Quijote de Orson Welles)', 'Trista Purcer', 70);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (71, 181, 'Grey Gardens', 'Mellisent Cordes', 71);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (72, 3, 'One Sunday Afternoon', 'Arnold Aked', 72);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (73, 87, 'My Mother''s Castle (Château de ma mère, Le)', 'Niki Grindrod', 73);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (74, 233, '20 Dates', 'Seka Arndell', 74);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (75, 139, 'Condemned, The', 'Ignatius Buske', 75);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (76, 232, 'Trailer Park Jesus', 'Daffy Krinks', 76);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (77, 144, 'Note by Note: The Making of Steinway L1037', 'Costa Aikett', 77);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (78, 208, 'Can Mr. Smith Get to Washington Anymore?', 'Bink Welchman', 78);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (79, 184, 'Playing from the Plate (Grajacy z talerza)', 'Obed Waddilow', 79);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (80, 97, 'A Summer in La Goulette', 'Tamra Botwood', 80);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (81, 210, 'Secret in Their Eyes, The (El secreto de sus ojos)', 'Kipp Barroux', 81);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (82, 121, 'Sweet Bird of Youth', 'Zonda Emmanuel', 82);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (83, 103, 'Magnum Cop', 'Adorne Tayler', 83);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (84, 53, 'Little Nikita', 'Wesley Bartram', 84);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (85, 218, 'Buried Alive', 'Bunni Tretter', 85);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (86, 95, 'Amazon Women on the Moon', 'Marje Treamayne', 86);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (87, 200, 'Rapt', 'Vanna Cronkshaw', 87);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (88, 1, 'Savage Three', 'Ignace Zuanazzi', 88);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (89, 183, 'Kiki''s Delivery Service', 'Shelly O''Scandall', 89);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (90, 156, 'Ghidorah, the Three-Headed Monster (San daikaijû: Chikyû saidai no kessen)', 'Calida Abarough', 90);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (91, 127, 'Are You Here', 'Nigel Tether', 91);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (92, 178, 'The Walking Stick', 'Biron Scollick', 92);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (93, 4, 'Little Buddha', 'Esme Scobbie', 93);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (94, 228, 'Flying Deuces, The', 'Ariadne Balle', 94);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (95, 208, 'Abraham', 'Nancee Salzburg', 95);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (96, 177, 'Suzanne''s Career (La carrière de Suzanne)', 'Lydia Pulham', 96);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (97, 11, 'What Dreams May Come', 'Christye MacNeilley', 97);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (98, 88, 'Ladrón que roba a ladrón', 'Irv Kincey', 98);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (99, 178, 'Quid Pro Quo', 'Nita Pashbee', 99);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (100, 94, 'East, The', 'Luisa Gerant', 100);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (101, 5, 'Land of the Lost', 'Nana Simone', 101);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (102, 98, 'Sleep Furiously', 'Yves Lates', 102);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (103, 130, 'Robot Stories', 'Gale Arter', 103);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (104, 227, 'Moderns, The', 'Brandyn Cadman', 104);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (105, 236, 'Dances Sacred and Profane', 'Shelbi Buttle', 105);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (106, 70, 'Love Exposure', 'Rhianna Redfern', 106);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (107, 153, 'Houdini', 'Finley Hacquel', 107);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (108, 29, 'Scusa ma ti chiamo amore', 'Effie Godman', 108);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (109, 114, 'Center Stage', 'Adolf Piche', 109);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (110, 193, 'Authors Anonymous', 'Dwayne Treeby', 110);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (111, 60, 'Until the Light Takes Us', 'Bogey Fearn', 111);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (112, 36, 'Messengers, The', 'Bibbye Hasluck', 112);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (113, 135, 'Fox and the Hound, The', 'Fifine Conor', 113);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (114, 48, 'Where the Boys Are ''84', 'Ryann Gosden', 114);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (115, 159, 'Oh, Heavenly Dog!', 'Alla Dautry', 115);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (116, 246, 'Immensee', 'Hilarius Fotherby', 116);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (117, 11, 'Jay and Silent Bob Go Down Under', 'Marisa Gobert', 117);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (118, 139, 'Hunter, The', 'Alfonse Pentycross', 118);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (119, 59, 'Hiroshima ', 'Evyn Packham', 119);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (120, 210, 'Barry Lyndon', 'Sherrie Annon', 120);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (121, 186, 'Loves of Carmen, The', 'Nat Lattos', 121);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (122, 113, 'Deadly Advice', 'Cariotta Walewicz', 122);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (123, 238, 'Clockwork Orange, A', 'Adela Guidone', 123);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (124, 183, 'Drum', 'Donn Tenbrug', 124);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (125, 195, 'Baytown Outlaws, The', 'Conny Copo', 125);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (126, 206, 'Slither', 'Philomena Etherington', 126);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (127, 90, 'Orlando', 'Simonne Stopps', 127);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (128, 121, 'Boxing Gym', 'Jenilee Strangward', 128);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (129, 182, 'It''s Alive III: Island of the Alive', 'Jacquelyn Domoni', 129);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (130, 164, 'Johnny 100 Pesos (Johnny cien pesos)', 'Fletcher Yanin', 130);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (131, 24, 'Map of the Human Heart', 'Roman Stain', 131);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (132, 64, 'Kick-Ass', 'Kylila Castelluzzi', 132);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (133, 200, 'Russell Peters: Outsourced', 'Antoine Forty', 133);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (134, 76, 'Private Life of Henry VIII, The', 'Percy Tebboth', 134);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (135, 42, 'The Well-Digger''s Daughter', 'Ester Gogarty', 135);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (136, 37, 'Playing for Keeps', 'Caresa Duncan', 136);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (137, 36, 'L.627', 'Johnathon Purton', 137);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (138, 180, 'Someday This Pain Will Be Useful to You', 'Bessie Lingard', 138);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (139, 132, 'Two Girls and a Guy', 'Iona Sylett', 139);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (140, 46, 'Bolero (Uns et les autres, Les)', 'Donny Cordeiro', 140);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (141, 98, 'Hell Is Sold Out', 'Linnie Macknish', 141);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (142, 187, 'Perfect', 'Clem Sowrah', 142);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (143, 92, 'Recipe for Love', 'Maryl Richardsson', 143);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (144, 236, 'Destruction Force', 'Ring Cammish', 144);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (145, 26, 'Horror Planet (a.k.a. Inseminoid)', 'Marcela Bennet', 145);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (146, 15, 'Arn: The Knight Templar (Arn - Tempelriddaren)', 'Alvie St. Hill', 146);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (147, 8, 'Advise and Consent', 'Zed Tenbrug', 147);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (148, 24, 'Cencoroll', 'Doroteya Jacobsen', 148);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (149, 223, 'Sister Act 2: Back in the Habit', 'Dallis Lacelett', 149);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (150, 151, 'Call of Cthulhu, The', 'Alfreda Flamank', 150);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (151, 142, 'View to a Kill, A', 'Miquela Hamstead', 151);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (152, 246, 'Harvey', 'Ingmar Goney', 152);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (153, 92, 'Moving Midway', 'Aubine Langdridge', 153);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (154, 185, 'It''s My Mother''s Birthday Today', 'Ardenia Wanka', 154);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (155, 247, 'Mr. Smith Goes to Washington', 'Rand Westley', 155);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (156, 84, 'Morocco', 'Syd Hoppner', 156);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (157, 152, 'Almost Heroes', 'Keelia Kield', 157);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (158, 195, 'Bewitched (Alter Ego)', 'Kaitlyn Wippermann', 158);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (159, 193, 'Kisses (Kuchizuke)', 'Karin Cansdale', 159);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (160, 91, 'In Their Skin', 'Carlin Kastel', 160);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (161, 136, 'Space Raiders', 'Nickie Le Moucheux', 161);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (162, 211, 'President''s Man: A Line in the Sand, The', 'Urbain Shilliday', 162);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (163, 218, 'Moulin Rouge', 'Aubrette Snoddon', 163);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (164, 107, 'Claire Dolan', 'Cristian Sully', 164);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (165, 43, 'G.I. Joe: The Movie', 'Cynthea Brightie', 165);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (166, 228, 'Casino Royale', 'Hamlin Bushrod', 166);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (167, 116, 'Blade on the Feather (Deep Cover)', 'Evan Ebourne', 167);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (168, 238, 'Witches, The', 'Dorelle Symcoxe', 168);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (169, 51, 'Cell Count', 'Cordelie Gaiford', 169);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (170, 97, 'Earth vs. the Flying Saucers', 'Lorenzo Dye', 170);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (171, 219, 'Children of the Living Dead', 'Catina Sulley', 171);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (172, 89, 'Sixpack (Pussikaljaelokuva)', 'Averil Proudlove', 172);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (173, 26, 'Fresh Bait (L''appât) ', 'Brucie Feasley', 173);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (174, 233, 'Bear''s Kiss', 'Caren Davidescu', 174);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (175, 125, 'Coco Chanel', 'Celestyn Pock', 175);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (176, 213, 'Snowtown (Snowtown Murders, The)', 'Bonnibelle Aylett', 176);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (177, 61, 'Stella', 'Ario Flay', 177);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (178, 139, 'Jimmy and Judy', 'Clyde McGahey', 178);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (179, 151, 'Adam and Dog', 'Zara Jordeson', 179);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (180, 53, 'Raising Cain', 'Cate Bridgestock', 180);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (181, 144, 'Easy to Love', 'Maurizia Flindall', 181);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (182, 136, 'Sexy Beast', 'Penny MacFie', 182);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (183, 62, 'Fast Lane', 'Cosme Perring', 183);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (184, 118, 'One Man Against the Organization', 'Freddy Thomsson', 184);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (185, 164, 'Adventures of Buckaroo Banzai Across the 8th Dimension, The', 'Bud Bisterfeld', 185);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (186, 9, 'Burrowing (Man tänker sitt)', 'Sarge Canada', 186);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (187, 142, 'Enemies: A Love Story', 'Correna Jacklin', 187);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (188, 235, 'Mighty Ducks, The', 'Darby Hattrick', 188);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (189, 167, 'Sixth Sense, The', 'Conroy Yeowell', 189);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (190, 217, 'Lightnin''', 'Claudina Gosselin', 190);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (191, 74, 'Mobsters', 'Margalo Falcus', 191);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (192, 62, 'James Gandolfini: Tribute to a Friend', 'Brit Cabena', 192);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (193, 56, 'Year Ago in Winter, A (Im Winter ein Jahr)', 'Aubry Behnecke', 193);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (194, 107, 'Springsteen & I', 'Tobey Cutteridge', 194);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (195, 63, 'Werewolf Woman (La lupa mannara)', 'Krista Ingree', 195);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (196, 61, 'Wanda', 'Bryna Starking', 196);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (197, 227, 'Affair in Trinidad', 'Mag Bugge', 197);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (198, 217, 'Baytown Outlaws, The', 'Jordanna Aggas', 198);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (199, 163, 'Omega Doom', 'Robbert Cobleigh', 199);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (200, 83, 'Journey to the Center of the Earth', 'Abigail Sanbroke', 200);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (201, 230, 'Never Give a Sucker an Even Break', 'Tully Tilling', 201);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (202, 149, 'Werewolf, The', 'Helenka Farlowe', 202);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (203, 167, 'WUSA', 'Davon Coolbear', 203);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (204, 32, 'Amira & Sam', 'Appolonia Addinall', 204);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (205, 184, 'Pushing Tin', 'Becca Dallender', 205);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (206, 47, 'Run, Simon, Run', 'Wilhelmine Meuse', 206);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (207, 175, 'I Know What I Saw', 'Norry Born', 207);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (208, 229, 'Viva Cuba', 'Johannes Codd', 208);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (209, 142, 'Switch', 'Gare Pether', 209);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (210, 101, 'Cuckoo in a Dark Forest (Kukacka v temném lese) ', 'Jillayne Mityukov', 210);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (211, 24, 'Saimaa Gesture, The (Saimaa-ilmiö)', 'Starr Serjent', 211);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (212, 63, 'Carpool', 'Sabrina Petris', 212);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (213, 59, 'Metro Manila', 'Gerhardine Balding', 213);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (214, 247, 'Fame', 'Yulma Lancastle', 214);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (215, 47, 'La petite reine', 'Ivette Putterill', 215);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (216, 180, 'Indian Runner, The', 'Sara-ann Brixey', 216);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (217, 51, 'Sea Wolf, The', 'Marion Moyser', 217);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (218, 141, 'Darling', 'Nicolais Bail', 218);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (219, 130, 'Do the Right Thing', 'Myrna Back', 219);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (220, 126, 'Fool''s Gold', 'Otto Hillan', 220);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (221, 51, 'Rendezvous', 'Justinian Leffek', 221);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (222, 43, 'Middle of Nowhere', 'Luigi Vasilov', 222);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (223, 113, 'Black', 'Bernardo Cumpton', 223);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (224, 71, 'Gorgeous (Boh lee chun)', 'Minette Eckart', 224);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (225, 63, 'All That... for This?!', 'Renato Bedwell', 225);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (226, 227, 'Fugitive, The', 'Anne Caunter', 226);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (227, 196, 'Notebook, The (A nagy füzet)', 'Michaelina Saenz', 227);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (228, 20, 'Night Listener, The', 'Jackelyn Owtram', 228);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (229, 248, 'Tennessee Johnson', 'Blake Tape', 229);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (230, 171, 'Twilight', 'Mirelle Kmiec', 230);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (231, 76, 'Book of Life, The', 'Moria Semens', 231);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (232, 13, 'Mr. Moto Takes a Chance', 'Dori Feighry', 232);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (233, 40, 'Afterburn', 'Cher Stennet', 233);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (234, 120, 'Like It Is', 'Sebastiano Kubera', 234);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (235, 19, 'Brother''s War', 'Kristoforo McComiskey', 235);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (236, 234, 'Undefeated, The', 'Alano Goublier', 236);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (237, 206, 'In a Town This Size', 'Lula Cockrem', 237);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (238, 77, 'For the Love of Movies', 'Garvy Attenbrough', 238);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (239, 4, 'Save the Date', 'Cort Ashe', 239);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (240, 41, 'The Lone Wolf Spy Hunt', 'Tymothy Merle', 240);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (241, 142, 'International, The', 'Wright Gewer', 241);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (242, 22, 'Sarah, Plain and Tall', 'Tani Kinson', 242);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (243, 235, 'Trespasser, The', 'Koral Spittal', 243);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (244, 61, 'The Uncommon Making of Petulia', 'Lebbie Gliddon', 244);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (245, 46, 'Crash Reel, The', 'Aurie Servante', 245);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (246, 57, 'Bachelor Weekend, The', 'Kellen Parkinson', 246);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (247, 215, 'ChromeSkull: Laid to Rest 2', 'Ashby Duncan', 247);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (248, 207, 'Two: The Story of Roman & Nyro', 'Lucine Henric', 248);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (249, 131, 'Unreal Dream: The Michael Morton Story, An', 'Mercie Bower', 249);
insert into film_final (film_id, ranking, film_title, director, genre_id) values (250, 154, 'Giant Mechanical Man, The', 'Isiahi Topliss', 250);
