create table film (
	film_id INT,
	ranking INT,
	film_title VARCHAR(250),
	director VARCHAR(50),
	genre_id VARCHAR(50)
);
insert into film (film_id, ranking, film_title, director, genre_id) values (1, 196, 'Belles on Their Toes', 'Lynn Kincade', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (2, 180, 'In Search of a Midnight Kiss', 'Yovonnda McKmurrie', 'Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (3, 110, 'Kill List', 'Putnem Coffin', 'Horror|Mystery|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (4, 221, 'Basic Instinct 2', 'Meryl Southby', 'Crime|Drama|Mystery|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (5, 217, 'Shadow of Angels (Schatten der Engel)', 'Elfrida Schule', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (6, 12, 'Seance (Kôrei)', 'Klarrisa Careswell', 'Drama|Horror|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (7, 233, 'Let Me In', 'Dory Leggate', 'Drama|Horror|Mystery');
insert into film (film_id, ranking, film_title, director, genre_id) values (8, 33, 'Stuff and Dough (Marfa si banii)', 'Joni Garber', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (9, 51, 'Fantomas', 'Vinnie Maldin', 'Adventure|Comedy|Crime|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (10, 44, 'Spirit Trap', 'Kitty Erdis', 'Horror|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (11, 83, 'Houseguest', 'Rhody MacDonough', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (12, 131, 'Friendly Persuasion', 'Luci Degoey', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (13, 87, 'Sansa', 'Rozalin Waller', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (14, 81, 'Tight Spot', 'Ketti Winterbourne', 'Drama|Film-Noir|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (15, 96, 'Snow White', 'Bone Whittet', 'Fantasy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (16, 47, 'Black Tights (1-2-3-4 ou Les Collants noirs)', 'Sherri Ashbee', 'Drama|Musical');
insert into film (film_id, ranking, film_title, director, genre_id) values (17, 11, 'CSNY Déjà Vu', 'Gale Bootyman', 'Documentary');
insert into film (film_id, ranking, film_title, director, genre_id) values (18, 230, 'Puppet Master III: Toulon''s Revenge', 'Ayn Trussman', 'Horror|Sci-Fi|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (19, 243, 'As If I Didn''t Exist (Elina - Som om jag inte fanns)', 'Rafe Dutton', 'Children|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (20, 199, 'Dragon Age: Blood mage no seisen (a.k.a. Dragon Age: Dawn of the Seeker)', 'Mahala Buckston', 'Animation|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (21, 31, 'Heart of Dragon (Long de xin)', 'Sarina Kastel', 'Action|Comedy|Crime|Drama|War');
insert into film (film_id, ranking, film_title, director, genre_id) values (22, 45, 'Housewarming (Travaux, on sait quand ça commence...)', 'Claire Farnaby', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (23, 241, 'Explorers', 'Sauveur Minty', 'Adventure|Children|Sci-Fi');
insert into film (film_id, ranking, film_title, director, genre_id) values (24, 198, 'Alamo Bay', 'Carolee Munday', 'Action|Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (25, 60, 'Things You Can Tell Just by Looking at Her', 'Lucie Iacobini', 'Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (26, 159, 'Tooth Fairy', 'Ruttger Nickolls', 'Comedy|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (27, 7, 'Neighbor, The', 'Jehu Ivashnikov', 'Horror|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (28, 138, 'Disorganized Crime', 'Olva Clynter', 'Action|Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (29, 30, 'Lady Takes a Chance, A', 'Ernaline Vice', 'Comedy|Romance|Western');
insert into film (film_id, ranking, film_title, director, genre_id) values (30, 235, 'Midnight Chronicles', 'Avivah Hinkens', 'Action|Adventure|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (31, 98, 'Jeepers Creepers', 'Boyd McKillop', 'Horror');
insert into film (film_id, ranking, film_title, director, genre_id) values (32, 21, 'Valley of the Bees (Údolí vcel)', 'Sibelle Sneesby', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (33, 21, 'Rampart', 'Sherry Talby', 'Action|Crime|Drama|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (34, 198, 'Outrage (Autoreiji)', 'Lauree Worsalls', 'Crime|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (35, 36, 'Busher, The', 'Aurea Scarsbrook', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (36, 12, 'Get Bruce', 'Antoni Gillott', 'Documentary');
insert into film (film_id, ranking, film_title, director, genre_id) values (37, 177, 'Red Baron, The (Der rote Baron)', 'Sophia Philippsohn', 'Action|Drama|Romance|War');
insert into film (film_id, ranking, film_title, director, genre_id) values (38, 117, 'Hollywood Homicide', 'Miriam Leyson', 'Action|Crime|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (39, 14, 'Unreal Dream: The Michael Morton Story, An', 'Beale Bazoge', 'Documentary');
insert into film (film_id, ranking, film_title, director, genre_id) values (40, 240, 'Too Hot to Handle', 'Laurena Greggs', 'Adventure|Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (41, 141, 'Fast Lane', 'Eleni Woolam', 'Action|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (42, 82, 'Dr. Dolittle 3', 'Haywood Marshallsay', 'Children|Comedy|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (43, 201, 'London', 'Caty Simmance', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (44, 81, 'Fireworks (Hana-bi)', 'Diahann Jobern', 'Crime|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (45, 26, 'Cypher', 'Reeva Newland', 'Action|Sci-Fi|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (46, 143, 'Kai Po Che!', 'Sig Lunk', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (47, 44, 'Loved Ones, The', 'Haze Roalfe', 'Horror');
insert into film (film_id, ranking, film_title, director, genre_id) values (48, 41, 'Falling Up', 'Gerrard Gerssam', 'Comedy|Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (49, 145, 'Blown Away', 'Jacenta Varsey', 'Action|Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (50, 142, 'Triplets of Belleville, The (Les triplettes de Belleville)', 'Sabine Meekins', 'Animation|Comedy|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (51, 183, 'Monsieur Vincent', 'Laurianne Connikie', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (52, 73, 'When a Stranger Calls', 'Bret Selby', 'Horror|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (53, 11, 'Dead Air', 'Becki Wozencroft', 'Horror|Sci-Fi|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (54, 242, 'Alaska', 'Sholom Gounet', 'Adventure|Children');
insert into film (film_id, ranking, film_title, director, genre_id) values (55, 215, 'House of Games', 'Christan Parvin', 'Crime|Film-Noir|Mystery|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (56, 35, 'Time Masters (Maîtres du temps, Les)', 'Kati Echelle', 'Animation|Sci-Fi');
insert into film (film_id, ranking, film_title, director, genre_id) values (57, 24, 'Darwin Awards, The', 'Harlie Adami', 'Adventure|Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (58, 146, 'Kissing Jessica Stein', 'Dewitt Asquez', 'Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (59, 130, 'Diary of the Dead', 'Michel Maken', 'Horror|Sci-Fi');
insert into film (film_id, ranking, film_title, director, genre_id) values (60, 176, 'Strike (Stachka)', 'Blithe Battle', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (61, 22, 'Secret Adventures of Tom Thumb, The', 'Taddeo Ondricek', 'Adventure|Animation');
insert into film (film_id, ranking, film_title, director, genre_id) values (62, 124, 'Chained for Life', 'Christos Bruck', 'Crime');
insert into film (film_id, ranking, film_title, director, genre_id) values (63, 91, 'Fred: The Movie', 'Lilia Currie', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (64, 65, 'Open Season', 'Jillana Vale', 'Adventure|Animation|Children|Comedy|IMAX');
insert into film (film_id, ranking, film_title, director, genre_id) values (65, 237, 'Magnificent Seven Ride!, The', 'Stirling Advani', 'Western');
insert into film (film_id, ranking, film_title, director, genre_id) values (66, 159, 'A Cinderella Story: Once Upon a Song', 'Ripley Bonett', 'Children|Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (67, 201, 'Not Here to Be Loved (Je ne suis pas là pour être aimé)', 'Carmencita Pittham', 'Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (68, 174, 'Perfect Game, The', 'Dean Swainsbury', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (69, 233, 'First Daughter', 'Blinnie Ockendon', 'Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (70, 102, '7th Heaven (Seventh Heaven)', 'Amos Gidley', 'Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (71, 149, 'The Time of Their Lives', 'Rhett Loftie', 'Comedy|Fantasy|Romance|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (72, 124, 'Splendor', 'Errick Bellson', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (73, 133, 'Dreamer: Inspired by a True Story', 'Devan Danielsohn', 'Children|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (74, 110, 'Army of Shadows (L''armée des ombres)', 'Chlo Sherborne', 'Action|Drama|Thriller|War');
insert into film (film_id, ranking, film_title, director, genre_id) values (75, 66, 'Who''s the Caboose?', 'Alain Stollen', 'Comedy|Documentary');
insert into film (film_id, ranking, film_title, director, genre_id) values (76, 235, 'Rhapsody in Blue', 'Jermain Carrel', 'Drama|Musical');
insert into film (film_id, ranking, film_title, director, genre_id) values (77, 178, 'Boston Strangler, The', 'Janene Miskimmon', 'Crime|Drama|Mystery|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (78, 69, 'Hometown Legend', 'Delora Cashen', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (79, 248, 'Garlic Is As Good As Ten Mothers', 'Harriet Snell', '(no genres listed)');
insert into film (film_id, ranking, film_title, director, genre_id) values (80, 24, 'Recess: School''s Out', 'Marv Esplin', 'Animation|Children');
insert into film (film_id, ranking, film_title, director, genre_id) values (81, 80, '13 Lakes', 'Calida Devinn', 'Documentary');
insert into film (film_id, ranking, film_title, director, genre_id) values (82, 184, 'Easy Life, The (Il Sorpasso)', 'Reinhard Danelet', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (83, 203, 'Suppose They Gave a War and Nobody Came?', 'Edi Sondon', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (84, 237, 'Cherry Crush', 'Akim Ivic', 'Drama|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (85, 45, 'Cabaret', 'Moselle Gallihawk', 'Drama|Musical');
insert into film (film_id, ranking, film_title, director, genre_id) values (86, 75, 'Green Lantern: Emerald Knights', 'Lesly Challiss', 'Action|Adventure|Animation|Children');
insert into film (film_id, ranking, film_title, director, genre_id) values (87, 202, 'Hotel New Hampshire, The', 'Chickie De Castri', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (88, 126, 'Thor: The Dark World', 'Martguerita Ellerker', 'Action|Adventure|Fantasy|IMAX');
insert into film (film_id, ranking, film_title, director, genre_id) values (89, 185, 'Gandhi', 'Lou McManamon', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (90, 228, 'Chill Out! (Descongélate!)', 'Lilli Beaty', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (91, 77, 'Just Add Water', 'Kesley Spary', 'Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (92, 155, 'Paradise, Hawaiian Style', 'Idette Glasser', 'Comedy|Musical');
insert into film (film_id, ranking, film_title, director, genre_id) values (93, 155, 'Before the Revolution (Prima della rivoluzione)', 'Phip Meenan', 'Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (94, 110, 'King''s Game (Kongekabale)', 'Theresina Huggins', 'Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (95, 4, 'Luna, La', 'Lyn Marcinkowski', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (96, 229, 'High Fidelity', 'Joyann Mayze', 'Comedy|Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (97, 36, 'Lara Croft Tomb Raider: The Cradle of Life', 'Dyanna Floyd', 'Action|Adventure|Comedy|Romance|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (98, 130, 'Convent, The (O Convento)', 'Kayne Cantera', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (99, 43, 'The Unexpected Love', 'Zak Pettie', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (100, 170, 'Penny Dreadful', 'Meir Lusty', 'Horror|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (101, 36, 'Three Stooges in Orbit, The', 'Gray Shevell', 'Comedy|Sci-Fi');
insert into film (film_id, ranking, film_title, director, genre_id) values (102, 12, 'Wild Grass (Herbes folles, Les)', 'Chrissie Burgne', 'Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (103, 231, 'Executioners (Xian dai hao xia zhuan)', 'Renaud Dodimead', 'Action|Comedy|Sci-Fi');
insert into film (film_id, ranking, film_title, director, genre_id) values (104, 172, 'Wedding Date, The', 'Beatriz Farquhar', 'Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (105, 75, 'Dog Tags', 'Ham Welch', 'Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (106, 181, 'Steppenwolf', 'Daniela Pattison', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (107, 181, 'Conversations with Other Women', 'Felita Shanklin', 'Comedy|Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (108, 169, 'Red Tent, The (Krasnaya palatka)', 'Brandon Whymark', 'Adventure|Drama|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (109, 206, 'California Solo', 'Nicko Calendar', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (110, 104, 'Run', 'Wynne Noyes', 'Action|Drama|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (111, 4, 'Bungee Jumping of Their Own (Beonjijeompeureul hada)', 'Ford Embling', 'Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (112, 64, 'Plymouth Adventure', 'Garv Curror', 'Adventure|Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (113, 22, 'Cabin Fever: Patient Zero', 'Emelda Faughnan', 'Horror|Sci-Fi|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (114, 206, 'Venus in Fur (La Vénus à la fourrure)', 'Erek Flintoff', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (115, 108, 'Momo', 'Elisabet Babidge', 'Animation|Children|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (116, 245, 'Executioner, The', 'Augusto Vokes', 'Drama|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (117, 34, 'Love and Other Disasters', 'Quent Izkovici', 'Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (118, 177, 'Luther the Geek', 'Alexei Houseman', 'Horror');
insert into film (film_id, ranking, film_title, director, genre_id) values (119, 76, 'Treasure of the Four Crowns', 'Drucy Ferrao', 'Adventure');
insert into film (film_id, ranking, film_title, director, genre_id) values (120, 159, 'Story of Yonosuke, A (Yokomichi Yonosuke)', 'Atlanta Bilofsky', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (121, 49, 'Scanners III: The Takeover (Scanner Force)', 'Tamma Ashwin', 'Action|Horror|Sci-Fi');
insert into film (film_id, ranking, film_title, director, genre_id) values (122, 28, 'Burning, The', 'Mada Whitters', 'Horror');
insert into film (film_id, ranking, film_title, director, genre_id) values (123, 48, 'Lost World, The', 'Meaghan Bagworth', 'Adventure|Sci-Fi');
insert into film (film_id, ranking, film_title, director, genre_id) values (124, 171, 'Platform (Zhantai)', 'Fabien Sammon', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (125, 142, 'Geographer Drank His Globe Away, The (Geograf globus propil)', 'Merlina Martina', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (126, 238, 'Rushmore', 'Shaun Winkle', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (127, 152, 'Jack the Giant Slayer', 'Zelig Pellett', 'Adventure|Fantasy|IMAX');
insert into film (film_id, ranking, film_title, director, genre_id) values (128, 16, 'Killer Crocodile', 'Cherida Yanez', 'Horror');
insert into film (film_id, ranking, film_title, director, genre_id) values (129, 200, 'Let No Man Write My Epitaph', 'Nady Markwell', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (130, 101, 'Poetry (Shi)', 'Davita Erangey', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (131, 199, 'Sergeant York', 'Cammi Cowan', 'Drama|War');
insert into film (film_id, ranking, film_title, director, genre_id) values (132, 187, 'Prince Avalanche', 'Tobie Gauvin', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (133, 211, 'Program, The', 'Ema Ephgrave', 'Action|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (134, 212, 'Cyberbully', 'Luis Bebbington', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (135, 86, 'State Witness, The (Swiadek koronny)', 'Isaak Treven', 'Action|Crime|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (136, 232, 'Tooth Fairy', 'Corabella Bachs', 'Comedy|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (137, 70, 'Unleashed (Danny the Dog)', 'Keith Swiggs', 'Action|Crime|Drama|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (138, 175, 'Rampart', 'Yasmin Haggart', 'Action|Crime|Drama|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (139, 159, 'Wonderland', 'Mervin Doody', 'Comedy|Documentary');
insert into film (film_id, ranking, film_title, director, genre_id) values (140, 249, 'Gilles'' Wife (La femme de Gilles)', 'Ester Cyples', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (141, 158, 'Nicht mein Tag', 'Madlin Joannet', 'Action|Comedy|Crime');
insert into film (film_id, ranking, film_title, director, genre_id) values (142, 102, 'King''s Game (Kongekabale)', 'Edwin Sherwell', 'Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (143, 223, 'Love Trap, The', 'Justinian Cretney', 'Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (144, 139, 'They Call Him Bulldozer (Lo chiamavano Bulldozer)', 'Arnaldo Ferruzzi', 'Action|Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (145, 237, 'Rise', 'Michell O''Hannay', 'Action|Horror|Mystery|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (146, 168, 'Under the Lighthouse Dancing', 'Clea Suddaby', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (147, 214, 'Castle of Blood', 'Diarmid Vasilyev', 'Horror');
insert into film (film_id, ranking, film_title, director, genre_id) values (148, 122, 'Dark, The', 'Lew McCooke', 'Horror|Mystery|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (149, 37, 'Racket, The', 'Monah Chapelhow', 'Crime|Film-Noir');
insert into film (film_id, ranking, film_title, director, genre_id) values (150, 151, 'SuperBabies: Baby Geniuses 2', 'Mitzi Geistmann', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (151, 48, 'Story of Three Loves, The', 'Elayne Alyonov', 'Drama|Musical|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (152, 34, 'Manhunt', 'Heddi Grosier', 'Horror|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (153, 180, 'Fright Night Part II', 'Ives Scoggan', 'Horror');
insert into film (film_id, ranking, film_title, director, genre_id) values (154, 113, 'Last Letter, The (La dernière lettre)', 'Sayers Lello', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (155, 79, 'The Killers', 'Vick Gooley', 'Crime');
insert into film (film_id, ranking, film_title, director, genre_id) values (156, 25, 'Beach Blanket Bingo', 'Ava Wrigley', 'Comedy|Musical');
insert into film (film_id, ranking, film_title, director, genre_id) values (157, 187, 'Komodo', 'Maribeth Cassy', 'Horror|Sci-Fi|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (158, 1, 'Generation X', 'Natale Pilfold', 'Action|Adventure|Sci-Fi');
insert into film (film_id, ranking, film_title, director, genre_id) values (159, 210, 'Batman: Under the Red Hood', 'Casar Mogford', 'Action|Animation');
insert into film (film_id, ranking, film_title, director, genre_id) values (160, 244, 'Marilena de la P7', 'Shay covino', 'Drama|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (161, 235, 'Taxi 4', 'Kalila Adran', 'Action|Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (162, 125, 'Puppetry of the Penis: Live at the Forum (Puppetry of the Penis: The Ancient Art of Genital Origami)', 'Tallie Gencke', 'Comedy|Documentary');
insert into film (film_id, ranking, film_title, director, genre_id) values (163, 207, 'Brighton Rock', 'Ursa Barnewelle', 'Crime|Drama|Film-Noir');
insert into film (film_id, ranking, film_title, director, genre_id) values (164, 1, 'Desert Heat (Inferno)', 'Addia Clunie', 'Action');
insert into film (film_id, ranking, film_title, director, genre_id) values (165, 156, 'Tough Enough (Knallhart)', 'Vida Mainland', 'Crime|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (166, 48, 'Darfur Now', 'Linn Crady', 'Documentary');
insert into film (film_id, ranking, film_title, director, genre_id) values (167, 94, 'Into the Woods', 'Pauletta Heaphy', 'Adventure|Comedy|Fantasy|Musical');
insert into film (film_id, ranking, film_title, director, genre_id) values (168, 125, 'Crackers', 'Brier Sondon', 'Action|Comedy|Crime|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (169, 239, 'Vicious Kind, The', 'Orella Folke', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (170, 118, 'Barcelona', 'Shannah Toppas', 'Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (171, 176, 'Hangman''s House', 'Arlan O''Mara', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (172, 156, 'Death of a Salesman', 'Kassandra Cobbing', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (173, 26, 'Kiki', 'Arni Feares', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (174, 162, 'Three Little Words', 'Kerk Martinez', 'Comedy|Musical|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (175, 155, 'Air Guitar Nation', 'Abigale Toal', 'Comedy|Documentary|Musical');
insert into film (film_id, ranking, film_title, director, genre_id) values (176, 120, 'Easy A', 'Craig Bertson', 'Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (177, 35, 'Ironclad 2: Battle for Blood', 'Virgilio Bickerdyke', 'Action|Adventure');
insert into film (film_id, ranking, film_title, director, genre_id) values (178, 160, 'Second Best', 'Park Clayal', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (179, 242, 'Alone for Christmas', 'Rozanna Althrope', 'Action|Children|Comedy|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (180, 126, 'Long John Silver', 'Tab Cridlon', 'Action|Adventure');
insert into film (film_id, ranking, film_title, director, genre_id) values (181, 146, 'Invasion of the Body Snatchers', 'Gizela Rippin', 'Horror|Sci-Fi|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (182, 90, 'Tigger Movie, The', 'Taddeo O''Halleghane', 'Animation|Children');
insert into film (film_id, ranking, film_title, director, genre_id) values (183, 210, 'Slacker 2011', 'Noelle Ulyat', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (184, 176, 'Svensson, Svensson - I nöd och lust', 'Bradney McDougal', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (185, 81, 'Delphine 1, Yvan 0', 'Dolly Mordie', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (186, 248, 'Stolen Kisses (Baisers volés)', 'Tonya Barbary', 'Comedy|Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (187, 114, 'Last Life in the Universe (Ruang rak noi nid mahasan)', 'Flinn Tackes', 'Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (188, 250, 'Fast Lane', 'Tamqrah Matyasik', 'Action|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (189, 95, 'Edison Kinetoscopic Record of a Sneeze', 'Lucine Torrisi', 'Documentary');
insert into film (film_id, ranking, film_title, director, genre_id) values (190, 58, 'Bring on the Night', 'Danella Tulleth', 'Documentary|Musical');
insert into film (film_id, ranking, film_title, director, genre_id) values (191, 13, 'Down to the Cellar (Do pivnice)', 'Hort Seamen', 'Adventure|Fantasy|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (192, 65, 'Cotton Mary', 'Ralph Offord', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (193, 249, 'Compliance', 'Travis Rainsdon', 'Drama|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (194, 23, 'Serious Moonlight', 'Alica Smythin', 'Comedy|Crime|Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (195, 28, 'Desperately Seeking Susan', 'Kissee Espinay', 'Comedy|Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (196, 20, '2:37', 'Darla Serfati', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (197, 13, 'Conspiracy of Torture, The (Beatrice Cenci)', 'Roderigo Aldrick', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (198, 144, 'Mr. Nice', 'Wilma Krolle', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (199, 62, 'Asterix at the Olympic Games (Astérix aux jeux olympiques)', 'Caryl Ruf', 'Adventure|Children|Comedy|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (200, 4, 'Opposing Force', 'Vladamir Extall', '(no genres listed)');
insert into film (film_id, ranking, film_title, director, genre_id) values (201, 151, 'Lavatory Lovestory (Ubornaya istoriya - lyubovnaya istoriya)', 'Augusta Emanuele', 'Animation');
insert into film (film_id, ranking, film_title, director, genre_id) values (202, 22, 'San Antonio', 'Cloris Romer', 'Western');
insert into film (film_id, ranking, film_title, director, genre_id) values (203, 19, 'Havre, Le', 'Berenice Millwall', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (204, 192, 'Rhinoceros', 'Beryle Plaid', 'Comedy|Drama|Fantasy|Mystery|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (205, 104, 'Rocks (Rad, Das)', 'Murdock Nyssens', 'Action|Animation|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (206, 157, 'Head Over Heels (De Pernas pro Ar)', 'Emmalynn Jorn', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (207, 212, 'Thomas Pynchon: A Journey into the Mind of P.', 'Hagen Northrop', 'Documentary');
insert into film (film_id, ranking, film_title, director, genre_id) values (208, 37, 'Bustin'' Loose', 'Veronica Rosone', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (209, 116, 'Duel', 'Marjie Pash', 'Action|Mystery|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (210, 1, 'PT 109', 'Wade Filipczak', 'Drama|War');
insert into film (film_id, ranking, film_title, director, genre_id) values (211, 87, 'Chance of a Lifetime, The', 'Elane Rennebach', 'Crime|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (212, 119, 'My Best Enemy (Mi mejor enemigo)', 'Kore Podd', 'Drama|War');
insert into film (film_id, ranking, film_title, director, genre_id) values (213, 187, 'Blind Spot: Hitler''s Secretary (Im toten Winkel - Hitlers Sekretärin)', 'May Camillo', 'Documentary');
insert into film (film_id, ranking, film_title, director, genre_id) values (214, 19, 'Sex & Drugs & Rock & Roll', 'Tarah Mariet', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (215, 140, '11.6', 'Jayne Crang', 'Crime|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (216, 28, 'The Black Devil', 'Esta Floyd', 'Comedy|Fantasy');
insert into film (film_id, ranking, film_title, director, genre_id) values (217, 247, 'Life is a Bed of Roses (Vie est un roman, La)', 'Mathew Radcliffe', 'Fantasy|Musical');
insert into film (film_id, ranking, film_title, director, genre_id) values (218, 20, 'Where the Boys Are ''84', 'Oralla MacColgan', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (219, 247, 'Raisin in the Sun, A', 'Terri Boschmann', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (220, 117, 'Sacrifice (Zhao shi gu er)', 'Elena Kingsly', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (221, 30, 'Homem Que Desafiou o Diabo, O', 'Jessika Couves', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (222, 187, 'Loggerheads', 'Daryl Pethybridge', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (223, 235, 'Sun Wind (Aurinkotuuli)', 'Care Crutchley', 'Drama|Sci-Fi');
insert into film (film_id, ranking, film_title, director, genre_id) values (224, 128, 'Faces of Schlock', 'Carmelina Warratt', 'Comedy|Horror');
insert into film (film_id, ranking, film_title, director, genre_id) values (225, 23, 'It''s a Small World', 'Caitlin Baptista', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (226, 247, 'Bonfire of the Vanities', 'Tine Moreinis', 'Comedy|Crime|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (227, 249, 'Five Fingers', 'Conrade Pagan', 'Drama|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (228, 187, 'The Last Train through Harecastle Tunnel', 'Lorant Hadye', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (229, 102, 'Hell House', 'Lainey Oki', 'Documentary');
insert into film (film_id, ranking, film_title, director, genre_id) values (230, 101, 'Jack Frost', 'Garner Di Bernardo', 'Children|Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (231, 21, 'Bridal Party in Hardanger, The (Brudeferden i Hardanger)', 'Thomasin Duckit', 'Drama|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (232, 9, 'Blow Dry (a.k.a. Never Better)', 'Simeon McGinly', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (233, 63, 'Letters to Father Jacob (Postia pappi Jaakobille)', 'Mickie Harower', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (234, 183, 'Conspiracy of Torture, The (Beatrice Cenci)', 'Sammy Shutler', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (235, 213, 'Summer at Grandpa''s, A (Dong dong de jia qi)', 'Dre Draayer', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (236, 137, 'Macross Plus', 'Gennifer Lethbury', 'Action|Drama|Sci-Fi|War');
insert into film (film_id, ranking, film_title, director, genre_id) values (237, 184, 'Pretty Devils', 'Griffie Romke', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (238, 81, 'Siberia', 'Chantal Elion', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (239, 148, 'It''s Complicated', 'Jessey Stedman', 'Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (240, 112, 'Love Me Tender', 'Opal Benley', 'Musical|Western');
insert into film (film_id, ranking, film_title, director, genre_id) values (241, 1, 'Free Fall', 'Dick O''Fallone', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (242, 174, 'Gertie the Dinosaur', 'Eldon Freiburger', 'Animation|Children|Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (243, 123, '42', 'Kayley Jervois', 'Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (244, 121, 'Rabbit Without Ears (Keinohrhasen)', 'Felicio Jarnell', 'Comedy|Romance');
insert into film (film_id, ranking, film_title, director, genre_id) values (245, 149, 'Woman, a Gun and a Noodle Shop, A (San qiang pai an jing qi)', 'Thurstan Hague', 'Comedy|Drama');
insert into film (film_id, ranking, film_title, director, genre_id) values (246, 97, 'Thing with Two Heads, The', 'Louise Rashleigh', 'Comedy|Horror|Sci-Fi');
insert into film (film_id, ranking, film_title, director, genre_id) values (247, 131, 'Horton Hears a Who!', 'Ferrell Mackrell', 'Adventure|Animation|Children|Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (248, 239, 'Long Weekend, The', 'Denys Thompson', 'Comedy');
insert into film (film_id, ranking, film_title, director, genre_id) values (249, 238, 'Children of the Living Dead', 'Jessee Butterick', 'Horror|Thriller');
insert into film (film_id, ranking, film_title, director, genre_id) values (250, 124, 'Eat Sleep Die (Äta sova dö)', 'Stevena Prisk', 'Drama');
