CREATE TABLE IF NOT EXISTS employees(
   user_id        INTEGER  NOT NULL PRIMARY KEY 
  ,name           VARCHAR(20) NOT NULL
  ,email          VARCHAR(32) NOT NULL
  ,gender         VARCHAR(6) NOT NULL
  ,Date_of_birth  VARCHAR(10) NOT NULL
  ,State_of_Birth VARCHAR(2) NOT NULL
  ,company_id     INTEGER  NOT NULL
  ,car_make       VARCHAR(13) NOT NULL
  ,car_model      VARCHAR(19) NOT NULL
  ,Car_value      INTEGER  NOT NULL
);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (77,'Ahmed Hagley','ahagley24@whitehouse.gov','Male','1/5/1985','SC',1,'Buick','Skylark',49014);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (16,'Mahmud Arndell','marndellf@furl.net','Female','11/25/1959','FL',1,'Lotus','Esprit',29759);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (22,'Eilis Allwright','eallwrightl@soup.io','Male','7/3/1979','FL',1,'Bentley','Continental GT',26927);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (14,'Arty Stappard','astappardd@blogspot.com','Female','4/26/1992','NV',1,'Lexus','SC',26660);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (67,'Angelita Brezlaw','abrezlaw1u@privacy.gov.au','Female','4/24/1992','DC',1,'Chevrolet','Equinox',49732);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (59,'Luca Etches','letches1m@moonfruit.com','Male','2/27/1997','AL',1,'Ford','F-Series Super Duty',16438);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (87,'Jacintha Huebner','jhuebner2e@so-net.ne.jp','Male','11/8/1996','FL',1,'Maybach','57',37401);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (27,'Monique Wibberley','mwibberleyq@cdc.gov','Female','9/4/1973','NJ',1,'Ford','Escape',41232);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (82,'Marmaduke Creser','mcreser29@howstuffworks.com','Male','3/6/1971','TX',2,'Mercedes-Benz','CLK-Class',15284);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (34,'Karyl Huburn','khuburnx@bravesites.com','Female','1/8/1971','CA',2,'Mercedes-Benz','E-Class',14827);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (44,'Robinson Hartland','rhartland17@ucla.edu','Female','5/5/1980','FL',2,'Mitsubishi','Mirage',46706);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (30,'Iain Heilds','iheildst@e-recht24.de','Male','4/13/1962','OK',2,'Buick','Riviera',19941);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (19,'Brittney Jickells','bjickellsi@ted.com','Male','10/13/1975','OH',2,'Maybach','57',37401);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (53,'Danie Hobbing','dhobbing1g@goo.gl','Female','12/6/1977','IL',2,'Ford','F-Series',49631);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (17,'Teodoor Locker','tlockerg@loc.gov','Female','12/7/1990','WV',2,'Nissan','200SX',43058);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (74,'Eada Stanislaw','estanislaw21@webeden.co.uk','Male','6/3/1981','CO',2,'Lotus','Esprit',13310);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (57,'Nico Balthasar','nbalthasar1k@blinklist.com','Female','3/23/1996','CA',3,'MINI','Cooper',39624);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (13,'Giacobo Crosher','gcrosherc@dion.ne.jp','Female','7/10/1969','IN',3,'Porsche','944',27824);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (1,'Raimondo Baudouin','rbaudouin0@ask.com','Male','11/4/1960','MN',3,'Saab','9000',36089);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (31,'Alli Lisamore','alisamoreu@virginia.edu','Female','2/7/1967','CA',3,'Buick','Skylark',49014);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (42,'Iago Routley','iroutley15@lycos.com','Male','11/14/1979','UT',3,'Nissan','200SX',43058);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (62,'Amitie Gamett','agamett1p@lycos.com','Female','5/18/1984','TX',3,'Lexus','SC',26660);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (69,'Ashley Squibbs','asquibbs1w@nps.gov','Female','11/24/1973','KS',3,'Porsche','911',23993);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (52,'Lindsay Rolfini','lrolfini1f@toplist.cz','Male','8/23/1995','OH',3,'Toyota','Avalon',32562);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (33,'Antoine Cancellor','acancellorw@yellowpages.com','Female','8/10/1988','CA',4,'Nissan','200SX',43058);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (79,'Ruthie Van der Beek','rvan26@gizmodo.com','Male','5/13/1983','IL',4,'Lexus','SC',26660);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (15,'Tyne Sail','tsaile@admin.ch','Female','8/5/1972','FL',4,'Saab','9000',36089);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (75,'Cleavland McTaggart','cmctaggart22@reference.com','Male','1/31/1964','OH',5,'Lexus','SC',26660);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (24,'Rosamund Auten','rautenn@discuz.net','Female','8/13/1988','CA',5,'Toyota','Avalon',32562);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (88,'Helaina Corry','hcorry2f@yolasite.com','Female','12/30/1958','OH',5,'Ford','F-Series Super Duty',16438);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (94,'Nadine Dyble','ndyble2l@lulu.com','Female','5/18/1997','MI',5,'Porsche','944',27824);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (32,'Des Climson','dclimsonv@sogou.com','Female','10/12/1994','AZ',5,'Bentley','Continental GT',26927);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (40,'Peadar Brockley','pbrockley13@nature.com','Male','8/2/1978','IN',5,'Lexus','LS',33954);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (54,'Terri Cockerham','tcockerham1h@bloglovin.com','Male','8/6/1971','WV',5,'MINI','Cooper',39624);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (38,'Randee McBeth','rmcbeth11@illinois.edu','Female','1/29/1989','MO',6,'Mitsubishi','Mirage',46706);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (6,'Hadlee Borrowman','hborrowman5@twitter.com','Male','9/20/1976','TX',6,'MINI','Cooper',39624);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (49,'Kerrie Lindeboom','klindeboom1c@eventbrite.com','Male','3/6/1985','KY',6,'Volkswagen','Passat',14056);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (98,'Hinze Nelthropp','hnelthropp2p@cdbaby.com','Female','11/21/1963','CA',6,'Lexus','SC',26660);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (71,'Tommi Husby','thusby1y@hao123.com','Male','1/6/1971','NY',6,'Ford','F-Series',49631);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (81,'Leslie Showell','lshowell28@paginegialle.it','Female','1/10/1958','TN',7,'Kia','Spectra',42395);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (92,'Carleen Wolters','cwolters2j@cloudflare.com','Male','11/15/1996','MS',7,'Ford','Escape',41232);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (48,'Paul Huntriss','phuntriss1b@phoca.cz','Female','10/17/1979','TN',7,'Mitsubishi','Mirage',46706);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (89,'Sallie Longson','slongson2g@chron.com','Male','11/15/1966','FL',7,'Mercedes-Benz','CLK-Class',15284);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (28,'Prisca Kibbey','pkibbeyr@weather.com','Female','1/6/1998','WA',7,'Buick','Skylark',49014);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (55,'Valentin Satterley','vsatterley1i@illinois.edu','Female','11/25/1982','MI',7,'Lotus','Esprit',29759);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (84,'Radcliffe Mellor','rmellor2b@nhs.uk','Male','9/12/1964','LA',7,'Buick','Riviera',19941);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (97,'Massimiliano Brideau','mbrideau2o@hc360.com','Male','11/21/1997','CA',8,'Bentley','Continental GT',26927);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (72,'Tedie McKane','tmckane1z@timesonline.co.uk','Female','8/27/1961','AL',8,'Lexus','LS',33954);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (37,'Rudolfo Sangster','rsangster10@mapy.cz','Male','6/15/1980','VA',8,'Kia','Spectra',42395);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (9,'Buddy Guile','bguile8@umn.edu','Female','11/24/1962','NV',8,'Mercedes-Benz','CLK-Class',15284);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (68,'Christoper Cockayne','ccockayne1v@rediff.com','Female','9/23/1993','FL',8,'Porsche','911',23993);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (21,'Winn Kunzel','wkunzelk@psu.edu','Male','1/9/1992','NY',8,'Buick','Riviera',19941);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (23,'Mufinella Tudhope','mtudhopem@europa.eu','Male','11/13/1978','MI',8,'Volkswagen','Passat',14056);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (73,'Bartolomeo Costall','bcostall20@businesswire.com','Female','9/15/1974','NY',8,'Jeep','Grand Cherokee',24063);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (95,'Muire Yurchishin','myurchishin2m@wufoo.com','Male','4/14/1990','VA',9,'Porsche','911',23993);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (58,'Suzette Hague','shague1l@blogtalkradio.com','Male','10/27/1972','PA',9,'Buick','Riviera',19941);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (25,'Leeann Molfino','lmolfinoo@symantec.com','Male','5/11/1976','NY',9,'Kia','Spectra',42395);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (90,'Mina Kelsall','mkelsall2h@boston.com','Female','11/18/1975','WA',9,'Saab','9000',36089);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (26,'Kym Seal','ksealp@arizona.edu','Male','9/25/1995','IN',10,'Ford','F-Series Super Duty',16438);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (63,'Fair Kubat','fkubat1q@washington.edu','Male','5/18/1986','KY',10,'Ford','Escape',41232);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (35,'Roxana Brunger','rbrungery@buzzfeed.com','Female','7/30/1981','CA',10,'Saab','9000',36089);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (86,'Nickola Dennick','ndennick2d@weibo.com','Female','9/5/1984','CO',10,'MINI','Cooper',39624);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (100,'Rhianna Bogie','rbogie2r@cbsnews.com','Male','7/27/1989','PA',10,'Mercedes-Benz','CLK-Class',15284);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (91,'Tommy McKall','tmckall2i@mlb.com','Female','8/31/1982','KS',10,'Mercedes-Benz','E-Class',14827);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (18,'Faith Christy','fchristyh@tamu.edu','Male','7/21/1977','TX',10,'Buick','Skylark',49014);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (56,'Neysa Tippin','ntippin1j@mit.edu','Female','1/22/1976','KS',11,'Ford','F-Series',49631);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (51,'Faun Woehler','fwoehler1e@walmart.com','Male','1/18/1996','SD',11,'Lotus','Esprit',13310);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (43,'Stephani Gallaher','sgallaher16@ucla.edu','Female','9/7/1975','TX',11,'Kia','Spectra',42395);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (41,'Job Walsh','jwalsh14@tmall.com','Male','2/23/1967','CT',11,'Bentley','Continental GT',26927);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (93,'Robers De Giorgi','rde2k@gnu.org','Male','11/28/1997','TX',11,'MINI','Cooper',39624);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (20,'Hercules Megson','hmegsonj@chron.com','Female','10/29/1994','NC',11,'Porsche','944',27824);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (83,'Filia Korda','fkorda2a@paypal.com','Female','10/24/1993','WA',11,'Mercedes-Benz','CLK-Class',15284);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (76,'Maggi Karus','mkarus23@google.com.hk','Male','10/24/1960','CO',12,'Chevrolet','Equinox',49732);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (5,'Ash Wrout','awrout4@plala.or.jp','Female','9/9/1982','WI',12,'Ford','F-Series Super Duty',16438);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (47,'Aaron Bernhardi','abernhardi1a@goodreads.com','Male','2/20/1960','VA',12,'Chevrolet','Traverse',29659);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (45,'Diane Lupton','dlupton18@paginegialle.it','Female','3/10/1972','VA',13,'Maybach','57',37401);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (29,'Erick Levett','elevetts@pcworld.com','Female','7/21/1992','CA',13,'Ford','F-Series',49631);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (8,'Rikki Hartill','rhartill7@mac.com','Male','12/28/1960','LA',13,'Mitsubishi','Mirage',46706);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (36,'Katie Meininking','kmeininkingz@constantcontact.com','Female','6/23/1978','FL',14,'Chevrolet','Traverse',29659);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (99,'Della Grigs','dgrigs2q@tiny.cc','Male','9/26/1968','CA',14,'Mercedes-Benz','CLK-Class',15284);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (3,'Adamo O''Towey','aotowey2@ovh.net','Male','4/11/1995','UT',14,'Ford','F-Series',49631);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (11,'Mitzi Gormley','mgormleya@oracle.com','Male','12/6/1997','IL',14,'Ford','F-Series Super Duty',16438);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (7,'Kacy Calley','kcalley6@ca.gov','Female','10/15/1984','CA',15,'Buick','Riviera',19941);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (61,'Brocky Grisdale','bgrisdale1o@ocn.ne.jp','Female','6/10/1986','IL',15,'Jeep','Grand Cherokee',24063);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (64,'Jodi Karpushkin','jkarpushkin1r@mapquest.com','Female','4/5/1996','FL',15,'MINI','Cooper',39624);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (65,'Christoffer Stiller','cstiller1s@goo.gl','Female','11/23/1964','TX',15,'Ford','F-Series',49631);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (39,'Cornelius Hunnisett','chunnisett12@google.ca','Male','6/26/1963','IA',15,'Lexus','LS',33954);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (70,'Marten Ceillier','mceillier1x@indiatimes.com','Male','6/21/1992','CT',15,'Kia','Spectra',42395);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (96,'Garrik Behrendsen','gbehrendsen2n@cdc.gov','Female','11/11/1967','CA',15,'Chevrolet','Equinox',49732);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (60,'Thebault Snodden','tsnodden1n@posterous.com','Male','11/9/1962','CA',15,'Bentley','Continental GT',26927);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (4,'Shep Astill','sastill3@drupal.org','Female','6/6/1995','CA',16,'Volkswagen','Passat',14056);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (80,'Gawen Trownson','gtrownson27@sphinn.com','Male','8/26/1965','TX',16,'Buick','Skylark',49014);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (46,'Stephi Provest','sprovest19@indiegogo.com','Female','7/26/1962','NV',16,'Ford','F-Series Super Duty',16438);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (66,'Billi Grimsdike','bgrimsdike1t@techcrunch.com','Male','1/22/1991','FL',16,'Kia','Spectra',42395);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (10,'Neddy Ortell','nortell9@woothemes.com','Male','8/23/1976','VA',17,'Saab','9000',36089);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (78,'Skippie Lambard','slambard25@goo.gl','Female','9/14/1969','CA',17,'Bentley','Continental GT',26927);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (85,'Art Axford','aaxford2c@etsy.com','Male','10/2/1995','NV',17,'Chevrolet','Traverse',29659);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (50,'Cyrill Fairebrother','cfairebrother1d@blogspot.com','Male','8/18/1967','KS',17,'Buick','Skylark',49014);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (12,'Gilburt Lau','glaub@diigo.com','Male','1/20/1982','CA',17,'Buick','Riviera',19941);
INSERT INTO employees(user_id,name,email,gender,Date_of_birth,State_of_Birth,company_id,car_make,car_model,Car_value) VALUES (2,'Kerianne Seyffert','kseyffert1@time.com','Female','4/1/1974','FL',17,'Lexus','SC',26660);
