var people = [
  {
    "id": 1,
    "first_name": "Moss",
    "last_name": "Tolliday",
    "email": "mtolliday0@elpais.com",
    "gender": "Male",
    "ip_address": "212.96.139.67"
  }, {
    "id": 2,
    "first_name": "Lorry",
    "last_name": "Simmonite",
    "email": "lsimmonite1@arstechnica.com",
    "gender": "Female",
    "ip_address": "162.184.248.146"
  }, {
    "id": 3,
    "first_name": "Karl",
    "last_name": "Mapes",
    "email": "kmapes2@google.com.au",
    "gender": "Male",
    "ip_address": "44.16.205.14"
  }, {
    "id": 4,
    "first_name": "Evangeline",
    "last_name": "Ridesdale",
    "email": "eridesdale3@t.co",
    "gender": "Female",
    "ip_address": "190.115.36.12"
  }, {
    "id": 5,
    "first_name": "Iona",
    "last_name": "Bowery",
    "email": "ibowery4@house.gov",
    "gender": "Female",
    "ip_address": "46.6.208.118"
  }, {
    "id": 6,
    "first_name": "Abram",
    "last_name": "Karoly",
    "email": "akaroly5@techcrunch.com",
    "gender": "Male",
    "ip_address": "165.13.137.24"
  }, {
    "id": 7,
    "first_name": "Zorina",
    "last_name": "Robottham",
    "email": "zrobottham6@github.com",
    "gender": "Female",
    "ip_address": "215.241.214.60"
  }, {
    "id": 8,
    "first_name": "Oliver",
    "last_name": "Bowering",
    "email": "obowering7@oaic.gov.au",
    "gender": "Male",
    "ip_address": "22.76.255.93"
  }, {
    "id": 9,
    "first_name": "Britteny",
    "last_name": "Lemin",
    "email": "blemin8@github.io",
    "gender": "Female",
    "ip_address": "129.235.6.255"
  }, {
    "id": 10,
    "first_name": "Gayler",
    "last_name": "Rintoul",
    "email": "grintoul9@sciencedaily.com",
    "gender": "Male",
    "ip_address": "199.116.239.14"
}]

module.exports = people;